# Generated by Django 6.0.6 on 2026-07-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mensagemcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
    ]
